"""Create AnimeData table

Revision ID: 44a3314ecbec
Revises: f5fdeb202f0e
Create Date: 2023-12-25 15:10:51.454993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44a3314ecbec'
down_revision = 'f5fdeb202f0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anime_filtered')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime_filtered',
    sa.Column('anime_id', sa.INTEGER(), nullable=False),
    sa.Column('genres', sa.VARCHAR(length=50), nullable=True),
    sa.Column('image_url', sa.TEXT(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('score', sa.TEXT(), nullable=True),
    sa.Column('synopsis', sa.TEXT(), nullable=True),
    sa.Column('type', sa.TEXT(), nullable=True),
    sa.Column('episodes', sa.INTEGER(), nullable=True),
    sa.Column('aired', sa.TEXT(), nullable=True),
    sa.Column('studios', sa.VARCHAR(length=50), nullable=True),
    sa.Column('duration', sa.TEXT(), nullable=True),
    sa.Column('rating', sa.TEXT(), nullable=True),
    sa.Column('rank', sa.INTEGER(), nullable=True),
    sa.Column('favorites', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('anime_id')
    )
    # ### end Alembic commands ###
