"""Initial migration

Revision ID: f5fdeb202f0e
Revises: 
Create Date: 2023-12-25 13:58:32.672405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5fdeb202f0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anime')
    op.drop_table('anime_dataset')
    with op.batch_alter_table('anime_filtered', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.Text(), nullable=True))
        batch_op.alter_column('score',
               existing_type=sa.FLOAT(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_column('licensors')
        batch_op.drop_column('source')
        batch_op.drop_column('japanese_name')
        batch_op.drop_column('genre')
        batch_op.drop_column('scored_by')
        batch_op.drop_column('image')
        batch_op.drop_column('premiered')
        batch_op.drop_column('members')
        batch_op.drop_column('producers')
        batch_op.drop_column('english_name')
        batch_op.drop_column('popularity')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=150), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.drop_column('user_name')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('user_name', sa.VARCHAR(length=1000), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('first_name')

    with op.batch_alter_table('anime_filtered', schema=None) as batch_op:
        batch_op.add_column(sa.Column('popularity', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('english_name', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('producers', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('members', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('premiered', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('scored_by', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('genre', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('japanese_name', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('licensors', sa.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('score',
               existing_type=sa.Text(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.drop_column('image_url')
        batch_op.drop_column('genres')

    op.create_table('anime_dataset',
    sa.Column('anime_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('score', sa.FLOAT(), nullable=True),
    sa.Column('genre', sa.VARCHAR(length=50), nullable=True),
    sa.Column('english_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('japanese_name', sa.TEXT(), nullable=True),
    sa.Column('synopsis', sa.TEXT(), nullable=True),
    sa.Column('type', sa.TEXT(), nullable=True),
    sa.Column('episodes', sa.VARCHAR(length=20), nullable=True),
    sa.Column('aired', sa.TEXT(), nullable=True),
    sa.Column('premiered', sa.TEXT(), nullable=True),
    sa.Column('producers', sa.VARCHAR(length=100), nullable=True),
    sa.Column('licensors', sa.VARCHAR(length=100), nullable=True),
    sa.Column('studios', sa.VARCHAR(length=50), nullable=True),
    sa.Column('source', sa.TEXT(), nullable=True),
    sa.Column('duration', sa.TEXT(), nullable=True),
    sa.Column('rating', sa.TEXT(), nullable=True),
    sa.Column('ranked', sa.TEXT(), nullable=True),
    sa.Column('popularity', sa.INTEGER(), nullable=True),
    sa.Column('members', sa.INTEGER(), nullable=True),
    sa.Column('favorites', sa.INTEGER(), nullable=True),
    sa.Column('watching', sa.INTEGER(), nullable=True),
    sa.Column('completed', sa.INTEGER(), nullable=True),
    sa.Column('on_hold', sa.INTEGER(), nullable=True),
    sa.Column('dropped', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('anime_id')
    )
    op.create_table('anime',
    sa.Column('anime_id', sa.INTEGER(), nullable=False),
    sa.Column('anime_img_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('anime_id')
    )
    # ### end Alembic commands ###
